// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dealer.proto

package proto;

public interface DealerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Dealer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, string&gt; model = 1;</code>
   */
  int getModelCount();
  /**
   * <code>map&lt;int32, string&gt; model = 1;</code>
   */
  boolean containsModel(
      int key);
  /**
   * Use {@link #getModelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.String>
  getModel();
  /**
   * <code>map&lt;int32, string&gt; model = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.String>
  getModelMap();
  /**
   * <code>map&lt;int32, string&gt; model = 1;</code>
   */
  /* nullable */
java.lang.String getModelOrDefault(
      int key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;int32, string&gt; model = 1;</code>
   */
  java.lang.String getModelOrThrow(
      int key);
}
