// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *name field single line comments
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *name field single line comments
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.proto.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.proto.Address address = 3;</code>
   * @return The address.
   */
  proto.Address getAddress();
  /**
   * <code>.proto.Address address = 3;</code>
   */
  proto.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  java.util.List<proto.Car> 
      getCarList();
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  proto.Car getCar(int index);
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  int getCarCount();
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  java.util.List<? extends proto.CarOrBuilder> 
      getCarOrBuilderList();
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  proto.CarOrBuilder getCarOrBuilder(
      int index);
}
