// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package proto;

/**
 * <pre>
 *
 *multi line comments
 * </pre>
 *
 *
 * Protobuf type {@code proto.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    car_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.PersonOuterClass.internal_static_proto_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.PersonOuterClass.internal_static_proto_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.Person.class, proto.Person.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   *name field single line comments
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *name field single line comments
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_ = 0;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private proto.Address address_;
  /**
   * <code>.proto.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.Address address = 3;</code>
   * @return The address.
   */
  @java.lang.Override
  public proto.Address getAddress() {
    return address_ == null ? proto.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.proto.Address address = 3;</code>
   */
  @java.lang.Override
  public proto.AddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? proto.Address.getDefaultInstance() : address_;
  }

  public static final int CAR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<proto.Car> car_;
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  @java.lang.Override
  public java.util.List<proto.Car> getCarList() {
    return car_;
  }
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.CarOrBuilder> 
      getCarOrBuilderList() {
    return car_;
  }
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  @java.lang.Override
  public int getCarCount() {
    return car_.size();
  }
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  @java.lang.Override
  public proto.Car getCar(int index) {
    return car_.get(index);
  }
  /**
   * <code>repeated .proto.Car car = 4;</code>
   */
  @java.lang.Override
  public proto.CarOrBuilder getCarOrBuilder(
      int index) {
    return car_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getAddress());
    }
    for (int i = 0; i < car_.size(); i++) {
      output.writeMessage(4, car_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAddress());
    }
    for (int i = 0; i < car_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, car_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.Person)) {
      return super.equals(obj);
    }
    proto.Person other = (proto.Person) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!getCarList()
        .equals(other.getCarList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getCarCount() > 0) {
      hash = (37 * hash) + CAR_FIELD_NUMBER;
      hash = (53 * hash) + getCarList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *multi line comments
   * </pre>
   *
   * Protobuf type {@code proto.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Person)
      proto.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.PersonOuterClass.internal_static_proto_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.PersonOuterClass.internal_static_proto_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Person.class, proto.Person.Builder.class);
    }

    // Construct using proto.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
        getCarFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      age_ = 0;
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      if (carBuilder_ == null) {
        car_ = java.util.Collections.emptyList();
      } else {
        car_ = null;
        carBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.PersonOuterClass.internal_static_proto_Person_descriptor;
    }

    @java.lang.Override
    public proto.Person getDefaultInstanceForType() {
      return proto.Person.getDefaultInstance();
    }

    @java.lang.Override
    public proto.Person build() {
      proto.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.Person buildPartial() {
      proto.Person result = new proto.Person(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(proto.Person result) {
      if (carBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          car_ = java.util.Collections.unmodifiableList(car_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.car_ = car_;
      } else {
        result.car_ = carBuilder_.build();
      }
    }

    private void buildPartial0(proto.Person result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.age_ = age_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.address_ = addressBuilder_ == null
            ? address_
            : addressBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.Person) {
        return mergeFrom((proto.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.Person other) {
      if (other == proto.Person.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (carBuilder_ == null) {
        if (!other.car_.isEmpty()) {
          if (car_.isEmpty()) {
            car_ = other.car_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCarIsMutable();
            car_.addAll(other.car_);
          }
          onChanged();
        }
      } else {
        if (!other.car_.isEmpty()) {
          if (carBuilder_.isEmpty()) {
            carBuilder_.dispose();
            carBuilder_ = null;
            car_ = other.car_;
            bitField0_ = (bitField0_ & ~0x00000008);
            carBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCarFieldBuilder() : null;
          } else {
            carBuilder_.addAllMessages(other.car_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              age_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              proto.Car m =
                  input.readMessage(
                      proto.Car.parser(),
                      extensionRegistry);
              if (carBuilder_ == null) {
                ensureCarIsMutable();
                car_.add(m);
              } else {
                carBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *name field single line comments
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *name field single line comments
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *name field single line comments
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *name field single line comments
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *name field single line comments
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {

      age_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000002);
      age_ = 0;
      onChanged();
      return this;
    }

    private proto.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.Address, proto.Address.Builder, proto.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.proto.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.proto.Address address = 3;</code>
     * @return The address.
     */
    public proto.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? proto.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    public Builder setAddress(proto.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    public Builder setAddress(
        proto.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    public Builder mergeAddress(proto.Address value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          address_ != null &&
          address_ != proto.Address.getDefaultInstance()) {
          getAddressBuilder().mergeFrom(value);
        } else {
          address_ = value;
        }
      } else {
        addressBuilder_.mergeFrom(value);
      }
      if (address_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000004);
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    public proto.Address.Builder getAddressBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    public proto.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            proto.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.proto.Address address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.Address, proto.Address.Builder, proto.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.Address, proto.Address.Builder, proto.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private java.util.List<proto.Car> car_ =
      java.util.Collections.emptyList();
    private void ensureCarIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        car_ = new java.util.ArrayList<proto.Car>(car_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Car, proto.Car.Builder, proto.CarOrBuilder> carBuilder_;

    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public java.util.List<proto.Car> getCarList() {
      if (carBuilder_ == null) {
        return java.util.Collections.unmodifiableList(car_);
      } else {
        return carBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public int getCarCount() {
      if (carBuilder_ == null) {
        return car_.size();
      } else {
        return carBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public proto.Car getCar(int index) {
      if (carBuilder_ == null) {
        return car_.get(index);
      } else {
        return carBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder setCar(
        int index, proto.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCarIsMutable();
        car_.set(index, value);
        onChanged();
      } else {
        carBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder setCar(
        int index, proto.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.set(index, builderForValue.build());
        onChanged();
      } else {
        carBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder addCar(proto.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCarIsMutable();
        car_.add(value);
        onChanged();
      } else {
        carBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder addCar(
        int index, proto.Car value) {
      if (carBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCarIsMutable();
        car_.add(index, value);
        onChanged();
      } else {
        carBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder addCar(
        proto.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.add(builderForValue.build());
        onChanged();
      } else {
        carBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder addCar(
        int index, proto.Car.Builder builderForValue) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.add(index, builderForValue.build());
        onChanged();
      } else {
        carBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder addAllCar(
        java.lang.Iterable<? extends proto.Car> values) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, car_);
        onChanged();
      } else {
        carBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder clearCar() {
      if (carBuilder_ == null) {
        car_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        carBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public Builder removeCar(int index) {
      if (carBuilder_ == null) {
        ensureCarIsMutable();
        car_.remove(index);
        onChanged();
      } else {
        carBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public proto.Car.Builder getCarBuilder(
        int index) {
      return getCarFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public proto.CarOrBuilder getCarOrBuilder(
        int index) {
      if (carBuilder_ == null) {
        return car_.get(index);  } else {
        return carBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public java.util.List<? extends proto.CarOrBuilder> 
         getCarOrBuilderList() {
      if (carBuilder_ != null) {
        return carBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(car_);
      }
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public proto.Car.Builder addCarBuilder() {
      return getCarFieldBuilder().addBuilder(
          proto.Car.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public proto.Car.Builder addCarBuilder(
        int index) {
      return getCarFieldBuilder().addBuilder(
          index, proto.Car.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Car car = 4;</code>
     */
    public java.util.List<proto.Car.Builder> 
         getCarBuilderList() {
      return getCarFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Car, proto.Car.Builder, proto.CarOrBuilder> 
        getCarFieldBuilder() {
      if (carBuilder_ == null) {
        carBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.Car, proto.Car.Builder, proto.CarOrBuilder>(
                car_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        car_ = null;
      }
      return carBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Person)
  }

  // @@protoc_insertion_point(class_scope:proto.Person)
  private static final proto.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.Person();
  }

  public static proto.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

