// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package proto;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Car_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\005proto\"]\n\006Person\022\014\n\004name\030" +
      "\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\037\n\007address\030\003 \001(\0132\016.pr" +
      "oto.Address\022\027\n\003car\030\004 \003(\0132\n.proto.Car\"8\n\007" +
      "Address\022\017\n\007postbox\030\001 \001(\005\022\016\n\006street\030\002 \001(\t" +
      "\022\014\n\004city\030\003 \001(\t\"V\n\003Car\022\014\n\004make\030\001 \001(\t\022\r\n\005m" +
      "odel\030\002 \001(\t\022\014\n\004year\030\003 \001(\005\022$\n\nbody_style\030\004" +
      " \001(\0162\020.proto.BodyStyle*7\n\tBodyStyle\022\013\n\007U" +
      "NKNOWN\020\000\022\t\n\005SEDAN\020\001\022\t\n\005COUPE\020\002\022\007\n\003SUV\020\003B" +
      "\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", "Car", });
    internal_static_proto_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Address_descriptor,
        new java.lang.String[] { "Postbox", "Street", "City", });
    internal_static_proto_Car_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Car_descriptor,
        new java.lang.String[] { "Make", "Model", "Year", "BodyStyle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
